/* Rebuild src/lib/signature/social.ts from Font Awesome's brand marks.

   The marks are drawn on different grids (facebook-f is 320x512, the rest
   448x512) and none of them fill their viewBox, so each glyph's real ink extent
   is measured here and carried alongside the path. The renderer places them by
   those bounds, which is what makes four different marks read as one size.

     node scripts/signature/build-social.mjs
*/

import { readFileSync, writeFileSync } from "node:fs";
import sharp from "sharp";

const DIR = "node_modules/@fortawesome/fontawesome-free/svgs/brands";
const OUT = "src/lib/signature/social.ts";

/* `optical` trims the letterform marks a little. Sized purely by ink height, a
   full-height "f" reads taller and heavier than an enclosed mark of the same
   measurement, so the letterforms come down a few percent to sit evenly. */
const ICONS = [
  { key: "instagram", file: "instagram", label: "Instagram", optical: 1 },
  { key: "linkedin", file: "linkedin-in", label: "LinkedIn", optical: 0.96 },
  { key: "x", file: "x-twitter", label: "X", optical: 0.98 },
  { key: "facebook", file: "facebook-f", label: "Facebook", optical: 0.92 },
];

async function inkBox(viewBox, d) {
  const [, , w, h] = viewBox;
  const png = await sharp(
    Buffer.from(
      `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${viewBox.join(" ")}"><path d="${d}" fill="#fff"/></svg>`
    )
  ).png().toBuffer();
  const { data, info } = await sharp(png).ensureAlpha().raw().toBuffer({ resolveWithObject: true });

  let x0 = Infinity, y0 = Infinity, x1 = -1, y1 = -1;
  for (let y = 0; y < info.height; y++) {
    for (let x = 0; x < info.width; x++) {
      if (data[(y * info.width + x) * info.channels + 3] > 40) {
        if (x < x0) x0 = x;
        if (x > x1) x1 = x;
        if (y < y0) y0 = y;
        if (y > y1) y1 = y;
      }
    }
  }
  return [x0, y0, x1, y1];
}

const entries = [];
for (const icon of ICONS) {
  const svg = readFileSync(`${DIR}/${icon.file}.svg`, "utf8");
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1].split(" ").map(Number);
  const d = svg.match(/ d="([^"]+)"/)[1];
  const box = await inkBox(viewBox, d);
  console.log(`${icon.key.padEnd(10)} ${icon.file.padEnd(12)} ink ${box.join(",")}`);
  entries.push({ ...icon, box, path: d });
}

const body = entries
  .map(
    (e) => `  ${e.key}: {
    key: ${JSON.stringify(e.key)},
    label: ${JSON.stringify(e.label)},
    optical: ${e.optical},
    box: [${e.box.join(", ")}],
    path: ${JSON.stringify(e.path)},
  },`
  )
  .join("\n");

writeFileSync(
  OUT,
  `/* Social marks for the signature card.

   Glyphs are Font Awesome Free 7 (icons CC BY 4.0, fontawesome.com/license/free),
   carried here as raw path data so the renderer needs no font or icon runtime.
   \`box\` is each glyph's measured ink extent inside its own viewBox — the marks
   are drawn on different grids, so they get placed by their real bounds rather
   than by the viewBox, which is what keeps them optically the same size.

   Generated by scripts/signature/build-social.mjs — edit that, not this. */

export type SocialGlyph = {
  key: string;
  label: string;
  /** optical size trim, relative to the shared ink height */
  optical: number;
  /** ink bounds inside the source viewBox: [x0, y0, x1, y1] */
  box: [number, number, number, number];
  path: string;
};

/** Glyphs only — which accounts they point at is a property of the brand. */
export const SOCIAL_GLYPHS: Record<string, SocialGlyph> = {
${body}
};
`
);
console.log(`\nwrote ${OUT}`);
