"use client";

import type { ComponentProps } from "react";
import * as Ph from "@phosphor-icons/react";
import type { Icon } from "@phosphor-icons/react";

/* Icon shim — Phosphor (duotone) re-exported under the lucide names the codebase uses.
 * Default weight = duotone (chic two-tone). Pass weight="fill"/"bold" to override.
 * Generated; do not hand-edit name mappings. */

export type LucideIcon = Icon;

function duo(Comp: Icon): Icon {
  const DuotoneIcon = (props: ComponentProps<Icon>) => <Comp weight="duotone" {...props} />;
  return DuotoneIcon as unknown as Icon;
}

/* Extra context icons (not lucide names) */
export const Moon: Icon = duo(Ph.MoonStars);
export const Confetti: Icon = duo(Ph.Confetti);
export const CellSignal: Icon = duo(Ph.CellSignalFull);
export const Battery: Icon = duo(Ph.BatteryFull);
export const WifiFull: Icon = duo(Ph.WifiHigh);

export const Accessibility: Icon = duo(Ph.Wheelchair);
export const Activity: Icon = duo(Ph.Pulse);
export const AlertCircle: Icon = duo(Ph.WarningCircle);
export const AlertTriangle: Icon = duo(Ph.Warning);
export const Apple: Icon = duo(Ph.AppleLogo);
export const ArrowDown: Icon = duo(Ph.ArrowDown);
export const ArrowDownLeft: Icon = duo(Ph.ArrowDownLeft);
export const ArrowLeft: Icon = duo(Ph.ArrowLeft);
export const ArrowRight: Icon = duo(Ph.ArrowRight);
export const ArrowUpDown: Icon = duo(Ph.ArrowsDownUp);
export const ArrowUpRight: Icon = duo(Ph.ArrowUpRight);
export const Award: Icon = duo(Ph.Medal);
export const Baby: Icon = duo(Ph.Baby);
export const BadgeCheck: Icon = duo(Ph.SealCheck);
export const Ban: Icon = duo(Ph.Prohibit);
export const Banknote: Icon = duo(Ph.Money);
export const BarChart3: Icon = duo(Ph.ChartBar);
export const Bell: Icon = duo(Ph.Bell);
export const BellOff: Icon = duo(Ph.BellSlash);
export const BellRing: Icon = duo(Ph.BellRinging);
export const BookOpen: Icon = duo(Ph.BookOpen);
export const Bookmark: Icon = duo(Ph.Bookmark);
export const Box: Icon = duo(Ph.Package);
export const Briefcase: Icon = duo(Ph.Briefcase);
export const Calendar: Icon = duo(Ph.CalendarBlank);
export const CalendarDays: Icon = duo(Ph.CalendarDots);
export const Camera: Icon = duo(Ph.Camera);
export const Car: Icon = duo(Ph.Car);
export const Check: Icon = duo(Ph.Check);
export const CheckCircle2: Icon = duo(Ph.CheckCircle);
export const ChefHat: Icon = duo(Ph.ChefHat);
export const ChevronDown: Icon = duo(Ph.CaretDown);
export const ChevronLeft: Icon = duo(Ph.CaretLeft);
export const ChevronRight: Icon = duo(Ph.CaretRight);
export const ChevronUp: Icon = duo(Ph.CaretUp);
export const ChevronsUpDown: Icon = duo(Ph.CaretUpDown);
export const CircleCheck: Icon = duo(Ph.CheckCircle);
export const CircleX: Icon = duo(Ph.XCircle);
export const ClipboardCheck: Icon = duo(Ph.ClipboardText);
export const ClipboardList: Icon = duo(Ph.ClipboardText);
export const Clock: Icon = duo(Ph.Clock);
export const Cloud: Icon = duo(Ph.Cloud);
export const CloudCheck: Icon = duo(Ph.CloudCheck);
export const CloudOff: Icon = duo(Ph.CloudSlash);
export const Code2: Icon = duo(Ph.Code);
export const CornerDownRight: Icon = duo(Ph.ArrowBendDownRight);
export const Cpu: Icon = duo(Ph.Cpu);
export const CreditCard: Icon = duo(Ph.CreditCard);
export const Crown: Icon = duo(Ph.Crown);
export const Database: Icon = duo(Ph.Database);
export const Download: Icon = duo(Ph.DownloadSimple);
export const Edit3: Icon = duo(Ph.PencilSimple);
export const Eye: Icon = duo(Ph.Eye);
export const EyeOff: Icon = duo(Ph.EyeSlash);
export const FileCheck: Icon = duo(Ph.FileText);
export const FileSignature: Icon = duo(Ph.Signature);
export const FileText: Icon = duo(Ph.FileText);
export const Filter: Icon = duo(Ph.Funnel);
export const Fingerprint: Icon = duo(Ph.Fingerprint);
export const Flag: Icon = duo(Ph.Flag);
export const Gavel: Icon = duo(Ph.Gavel);
export const Globe: Icon = duo(Ph.Globe);
export const GraduationCap: Icon = duo(Ph.GraduationCap);
export const Handshake: Icon = duo(Ph.Handshake);
export const Hash: Icon = duo(Ph.Hash);
export const Headset: Icon = duo(Ph.Headset);
export const Heart: Icon = duo(Ph.Heart);
export const HeartCrack: Icon = duo(Ph.HeartBreak);
export const Home: Icon = duo(Ph.House);
export const Hourglass: Icon = duo(Ph.Hourglass);
export const Image: Icon = duo(Ph.Image);
export const ImageOff: Icon = duo(Ph.ImageBroken);
export const Inbox: Icon = duo(Ph.Tray);
export const Info: Icon = duo(Ph.Info);
export const Instagram: Icon = duo(Ph.InstagramLogo);
export const XLogo: Icon = duo(Ph.XLogo);
export const TikTok: Icon = duo(Ph.TiktokLogo);
export const WhatsApp: Icon = duo(Ph.WhatsappLogo);
export const Share: Icon = duo(Ph.ShareNetwork);
export const LinkSimple: Icon = duo(Ph.LinkSimple);
export const Key: Icon = duo(Ph.Key);
export const KeyRound: Icon = duo(Ph.Key);
export const Languages: Icon = duo(Ph.Translate);
export const Layers: Icon = duo(Ph.Stack);
export const ListChecks: Icon = duo(Ph.ListChecks);
export const Loader2: Icon = duo(Ph.CircleNotch);
export const Lock: Icon = duo(Ph.Lock);
export const LogIn: Icon = duo(Ph.SignIn);
export const LogOut: Icon = duo(Ph.SignOut);
export const Mail: Icon = duo(Ph.Envelope);
export const MapPin: Icon = duo(Ph.MapPin);
export const Menu: Icon = duo(Ph.List);
export const MessageCircle: Icon = duo(Ph.ChatCircle);
export const Minus: Icon = duo(Ph.Minus);
export const MoreHorizontal: Icon = duo(Ph.DotsThree);
export const MoreVertical: Icon = duo(Ph.DotsThreeVertical);
export const MousePointerClick: Icon = duo(Ph.CursorClick);
export const Navigation: Icon = duo(Ph.NavigationArrow);
export const Palette: Icon = duo(Ph.Palette);
export const Paperclip: Icon = duo(Ph.Paperclip);
export const Pause: Icon = duo(Ph.Pause);
export const PauseCircle: Icon = duo(Ph.PauseCircle);
export const PenTool: Icon = duo(Ph.PenNib);
export const Pencil: Icon = duo(Ph.Pencil);
export const Phone: Icon = duo(Ph.Phone);
export const Pill: Icon = duo(Ph.Pill);
export const Plus: Icon = duo(Ph.Plus);
export const Quote: Icon = duo(Ph.Quotes);
export const Receipt: Icon = duo(Ph.Receipt);
export const RefreshCw: Icon = duo(Ph.ArrowsClockwise);
export const Rocket: Icon = duo(Ph.Rocket);
export const Save: Icon = duo(Ph.FloppyDisk);
export const Scale: Icon = duo(Ph.Scales);
export const ScrollText: Icon = duo(Ph.Scroll);
export const Search: Icon = duo(Ph.MagnifyingGlass);
export const SearchX: Icon = duo(Ph.MagnifyingGlassMinus);
export const Send: Icon = duo(Ph.PaperPlaneTilt);
export const Server: Icon = duo(Ph.HardDrives);
export const ServerCrash: Icon = duo(Ph.WarningOctagon);
export const Settings: Icon = duo(Ph.Gear);
export const Shield: Icon = duo(Ph.Shield);
export const ShieldAlert: Icon = duo(Ph.ShieldWarning);
export const ShieldCheck: Icon = duo(Ph.ShieldCheck);
export const SlidersHorizontal: Icon = duo(Ph.SlidersHorizontal);
export const Smartphone: Icon = duo(Ph.DeviceMobile);
export const Smile: Icon = duo(Ph.Smiley);
export const Sparkles: Icon = duo(Ph.Sparkle);
export const Square: Icon = duo(Ph.Square);
export const Star: Icon = duo(Ph.Star);
export const StickyNote: Icon = duo(Ph.Note);
export const Table: Icon = duo(Ph.Table);
export const Tag: Icon = duo(Ph.Tag);
export const Target: Icon = duo(Ph.Target);
export const Trash2: Icon = duo(Ph.Trash);
export const TrendingDown: Icon = duo(Ph.TrendDown);
export const TrendingUp: Icon = duo(Ph.TrendUp);
export const Type: Icon = duo(Ph.TextT);
export const Upload: Icon = duo(Ph.UploadSimple);
export const User: Icon = duo(Ph.User);
export const UserCheck: Icon = duo(Ph.UserCheck);
export const UserCircle: Icon = duo(Ph.UserCircle);
export const UserCog: Icon = duo(Ph.UserGear);
export const UserPlus: Icon = duo(Ph.UserPlus);
export const UserSearch: Icon = duo(Ph.UserFocus);
export const UserX: Icon = duo(Ph.UserMinus);
export const Users: Icon = duo(Ph.Users);
export const Wallet: Icon = duo(Ph.Wallet);
export const Wand2: Icon = duo(Ph.MagicWand);
export const Wifi: Icon = duo(Ph.WifiHigh);
export const Wrench: Icon = duo(Ph.Wrench);
export const X: Icon = duo(Ph.X);
export const XCircle: Icon = duo(Ph.XCircle);
export const Zap: Icon = duo(Ph.Lightning);
