/* Social marks for the signature card.

   Glyphs are Font Awesome Free 7 (icons CC BY 4.0, fontawesome.com/license/free),
   carried here as raw path data so the renderer needs no font or icon runtime.
   `box` is each glyph's measured ink extent inside its own viewBox — the marks
   are drawn on different grids, so they get placed by their real bounds rather
   than by the viewBox, which is what keeps them optically the same size.

   Generated by scripts/signature/build-social.mjs — edit that, not this. */

export type SocialIcon = {
  key: string;
  label: string;
  href: string;
  /** optical size trim, relative to the shared ink height */
  optical: number;
  /** ink bounds inside the source viewBox: [x0, y0, x1, y1] */
  box: [number, number, number, number];
  path: string;
};

export const SOCIALS: SocialIcon[] = [
  {
    key: "instagram",
    label: "Instagram",
    href: "https://www.instagram.com/emotion_mena/",
    optical: 1,
    box: [0, 31, 447, 479],
    path: "M224.3 141a115 115 0 1 0 -.6 230 115 115 0 1 0 .6-230zm-.6 40.4a74.6 74.6 0 1 1 .6 149.2 74.6 74.6 0 1 1 -.6-149.2zm93.4-45.1a26.8 26.8 0 1 1 53.6 0 26.8 26.8 0 1 1 -53.6 0zm129.7 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM399 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z",
  },
  {
    key: "linkedin",
    label: "LinkedIn",
    href: "https://www.linkedin.com/company/emotionmena/",
    optical: 0.96,
    box: [0, 0, 447, 447],
    path: "M100.3 448l-92.9 0 0-299.1 92.9 0 0 299.1zM53.8 108.1C24.1 108.1 0 83.5 0 53.8 0 39.5 5.7 25.9 15.8 15.8s23.8-15.8 38-15.8 27.9 5.7 38 15.8 15.8 23.8 15.8 38c0 29.7-24.1 54.3-53.8 54.3zM447.9 448l-92.7 0 0-145.6c0-34.7-.7-79.2-48.3-79.2-48.3 0-55.7 37.7-55.7 76.7l0 148.1-92.8 0 0-299.1 89.1 0 0 40.8 1.3 0c12.4-23.5 42.7-48.3 87.9-48.3 94 0 111.3 61.9 111.3 142.3l0 164.3-.1 0z",
  },
  {
    key: "x",
    label: "X",
    href: "https://x.com/EmotionMena",
    optical: 0.98,
    box: [0, 48, 447, 463],
    path: "M357.2 48L427.8 48 273.6 224.2 455 464 313 464 201.7 318.6 74.5 464 3.8 464 168.7 275.5-5.2 48 140.4 48 240.9 180.9 357.2 48zM332.4 421.8l39.1 0-252.4-333.8-42 0 255.3 333.8z",
  },
  {
    key: "facebook",
    label: "Facebook",
    href: "https://www.facebook.com/EmotionMENA",
    optical: 0.92,
    box: [14, 0, 305, 511],
    path: "M80 299.3l0 212.7 116 0 0-212.7 86.5 0 18-97.8-104.5 0 0-34.6c0-51.7 20.3-71.5 72.7-71.5 16.3 0 29.4 .4 37 1.2l0-88.7C291.4 4 256.4 0 236.2 0 129.3 0 80 50.5 80 159.4l0 42.1-66 0 0 97.8 66 0z",
  },
];
